# **Part 1 - DATA PREPROCESSING**

## **Importing the *Mathematical* Libraries**

In [ ]:
import numpy as np 
import pandas as pd
import math
import tensorflow as tf

In [ ]:
tf.__version__

'2.2.0'

# **Importing the Graphical Libraries**

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns


# **Importing the Dataset**

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(5)

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

# **Getting some information from the Dataset**

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [ ]:
dataset.describe()

RowNumber    CustomerId  ...  EstimatedSalary        Exited
count  10000.00000  1.000000e+04  ...     10000.000000  10000.000000
mean    5000.50000  1.569094e+07  ...    100090.239881      0.203700
std     2886.89568  7.193619e+04  ...     57510.492818      0.402769
min        1.00000  1.556570e+07  ...        11.580000      0.000000
25%     2500.75000  1.562853e+07  ...     51002.110000      0.000000
50%     5000.50000  1.569074e+07  ...    100193.915000      0.000000
75%     7500.25000  1.575323e+07  ...    149388.247500      0.000000
max    10000.00000  1.581569e+07  ...    199992.480000      1.000000

[8 rows x 11 columns]

In [ ]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [ ]:
dataset['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

# **Splittin the  data between independent variable and dependednt variable**

In [ ]:
X = dataset[['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary']].values
y = dataset['Exited'].values

# Another way to get the data
# X = dataset.iloc[:, 3:-1].values
# y = dataset.iloc[:, -1].values

In [ ]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [ ]:
y

array([1, 0, 1, ..., 1, 1, 0])

# **Enconding Categorical data**

### **Label Enconding the 'Gender' column**

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:, 2])

In [ ]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

### **One Hot Enconding for 'Geography' column**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[1])], remainder = 'passthrough')
X  = np.array(ct.fit_transform(X))


In [ ]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

# **Splitting the dataset into the Training set and Test set**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state= 0)

# **Feature Scaling**

In [ ]:
from sklearn.preprocessing import StandardScaler
sc  = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [ ]:
X_test

array([[-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# **Part 2 - BUILDING THE ANN**

## **Initializing the ANN**

In [ ]:
ann = tf.keras.models.Sequential()

## **Adding the input layer and the first hidden layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))

## **Adding the second hidden layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6, activation= 'relu'))

## **Adding the output layer**

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1, activation= 'sigmoid'))

# **Part 3 - TRAINING THE ANN**

## **Compiling the ANN**

In [ ]:
ann.compile(optimizer= 'adam',loss= 'binary_crossentropy',metrics= ['accuracy'])

## **Training the ANN on the Training set**



In [ ]:
ann.fit(X_train, y_train, batch_size= 32, epochs= 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6023 - accuracy: 0.7245
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4886 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4595 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4453 - accuracy: 0.7971
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4367 - accuracy: 0.8034
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4315 - accuracy: 0.8040
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4279 - accuracy: 0.8075
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4252 - accuracy: 0.8100
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4229 - accuracy: 0.8120
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4210 - accura

# **Part 4 - MAKING THE PREDICTIONS AND EVALUATING THE MODEL**

## **Predicting the result of a single observation**

In [ ]:
customer = [['France',600,'Male',40,3,60000,2, 1,1,50000]]

In [ ]:
# To do in another way

In [ ]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

array([[0.0463906]], dtype=float32)

In [ ]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])) > 0.5

array([[False]])

## **Predicting the results using the Test set**



In [ ]:
y_pred = []
for x in ann.predict(X_test):
  if x > 0.5: y_pred.append(1)
  else: y_pred.append(0)

y_pred = np.array(y_pred)

# Another way of doing it ( MORE EFFICIENT )
# y_pred = (y_pred > 0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## **Making the confusion Matrix and the Classification report**



In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [ ]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))

Confusion Matrix
[[1516   79]
 [ 203  202]]


In [ ]:
print('Classification Report')
print(classification_report(y_test,y_pred))

Classification Report
              precision    recall  f1-score   support

           0       0.88      0.95      0.91      1595
           1       0.72      0.50      0.59       405

    accuracy                           0.86      2000
   macro avg       0.80      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000



In [ ]:
accuracy_score(y_test, y_pred)

0.859